CREATE TABLE IF NOT EXISTS votes (
	id INTEGER NOT NULL,
	proposalId TEXT NOT NULL,
	choiceId INTEGER NOT NULL,
	address TEXT NOT NULL,
	sig TEXT NOT NULL,
	amount TEXT DEFAULT NULL,
	timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS snapshots (
	id INTEGER NOT NULL,
	snapshotBlock INTEGER NOT NULL,
	address TEXT NOT NULL,
	amount TEXT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS proposals (
	proposalId TEXT NOT NULL,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	options TEXT NOT NULL,
	snapshotBlock INTEGER NOT NULL,
	endBlock INTEGER NOT NULL,
	voteCount INTEGER NOT NULL DEFAULT 0,
	histogram TEXT NOT NULL,
	timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (proposalId)
);
